version: '2.4'
services:
  app:
    container_name: app
    build: .
    expose:
      - 80
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./.env:/app/.env
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_healthy

  db:
    image: mysql:5.7.29
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Dk^11w.Q89
      MYSQL_DATABASE: storage
      MYSQL_ROOT_PASSWORD: Kd98qw11#

  cache:
    image: redis:4.0.9
    container_name: redis
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10